"""add signoff_style and custom_instructions to clients

Revision ID: 292ab58b3169
Revises: d6314f16e38c
Create Date: 2026-09-26 13:27:21.413953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '292ab58b3169'
down_revision = 'd6314f16e38c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signoff_style', sa.String(length=20), server_default='NONE', nullable=False))
        batch_op.add_column(sa.Column('custom_instructions', sa.Text(), nullable=True))

    # ### end Alembic commands ###

    # Preserve existing behaviour: any client who already has an owner_name
    # set was already getting a personal sign-off before this migration —
    # don't silently drop it back to no-sign-off for them.
    op.execute("UPDATE clients SET signoff_style = 'OWNER_NAME' WHERE owner_name IS NOT NULL AND owner_name != ''")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('custom_instructions')
        batch_op.drop_column('signoff_style')

    # ### end Alembic commands ###
