"""add backlog tracking fields to clients

Revision ID: 46838d099bd9
Revises: b71c4f1c4083
Create Date: 2026-09-26 09:56:23.958297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46838d099bd9'
down_revision = 'b71c4f1c4083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('backlog_requested', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('backlog_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('backlog_review_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('backlog_charge_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('backlog_charge_id')
        batch_op.drop_column('backlog_review_count')
        batch_op.drop_column('backlog_status')
        batch_op.drop_column('backlog_requested')

    # ### end Alembic commands ###
