"""add gbp_review_path and stripe_subscription_item_id to locations

Revision ID: 610dd02d0882
Revises: 607f36fb195c
Create Date: 2026-09-20 18:37:10.422408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '610dd02d0882'
down_revision = '607f36fb195c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gbp_review_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('stripe_subscription_item_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_column('stripe_subscription_item_id')
        batch_op.drop_column('gbp_review_path')

    # ### end Alembic commands ###
