"""add reply_cadence to clients and scheduled_post_at to replies

Revision ID: b71c4f1c4083
Revises: 610dd02d0882
Create Date: 2026-09-22 20:12:40.044604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b71c4f1c4083'
down_revision = '610dd02d0882'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reply_cadence', sa.String(length=50), nullable=True))

    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_post_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.drop_column('scheduled_post_at')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('reply_cadence')

    # ### end Alembic commands ###
