"""drop unused founder_tier column and founder_counter table

Revision ID: d6314f16e38c
Revises: f9aeb566eb89
Create Date: 2026-09-26 12:35:24.886269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6314f16e38c'
down_revision = 'f9aeb566eb89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('founder_counter')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('founder_tier')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('founder_tier', sa.BOOLEAN(), autoincrement=False, nullable=False))

    op.create_table('founder_counter',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('founder_counter_pkey'))
    )
    # ### end Alembic commands ###
