"""add google reconnect tracking fields

Revision ID: f9aeb566eb89
Revises: 46838d099bd9
Create Date: 2026-09-26 12:22:13.131885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9aeb566eb89'
down_revision = '46838d099bd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_needs_reconnect', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('google_reconnect_notified_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('google_reconnect_notified_at')
        batch_op.drop_column('google_needs_reconnect')

    # ### end Alembic commands ###
